apiVersion: v1
kind: Service
metadata:
  name: "{{ printf "fw-%s" .Release.Name }}"
spec:
  type: NodePort
  ports:
  - port: {{ .Values.forwardPort }}
    nodePort: {{ .Values.forwardPort_Nodeport }}
    name: forwardport
  selector:
    component: "{{ printf "fw-%s-0" .Release.Name }}"
